export type Lesson = {
  id: string;
  title: string;
  description: string;
  project: string;
  skills: string[];
  href: string;
};

export const lessonDurationsMinutes: Record<string, number> = {
  "web-basics": 35,
  "how-the-web-works": 65,
  "html-css": 45,
  "html-semantics": 40,
  "html-forms-accessibility": 50,
  "web-accessibility": 60,
  "css-box-model": 40,
  "css-flex-responsive": 55,
  "css-grid-layouts": 55,
  "css-modern-styling": 55,
  "tailwind-foundations": 55,
  "tailwind-layout-responsive": 55,
  "tailwind-states-dark-mode": 50,
  "tailwind-customization": 55,
  "tailwind-reuse-production": 55,
  "bootstrap-foundations": 50,
  "bootstrap-grid-layout": 55,
  "bootstrap-components": 55,
  "bootstrap-javascript": 55,
  "bootstrap-customization-a11y": 50,
  "javascript-intro": 50,
  "javascript-logic": 55,
  "javascript-arrays-objects": 60,
  "javascript-dom-forms": 65,
  "javascript-scope-closures": 70,
  "javascript-this-prototypes": 70,
  "javascript-async-event-loop": 75,
  "javascript-fetch-errors": 70,
  "javascript-modules-patterns": 65,
  "javascript-interview-drills": 80,
  "git-github": 55,
  "agile-scrum-kanban": 45,
  "job-ready-practice": 60,
  "milestone-projects": 70,
  "code-review-practice": 70,
  "typescript-foundations": 55,
  "typescript-unions-narrowing": 60,
  "typescript-functions": 55,
  "typescript-generics": 60,
  "typescript-utility-types": 60,
  "typescript-safety-config": 55,
  "typescript-declarations": 50,
  "testing-debugging": 70,
  "build-tools": 60,
  "react-rendering-model": 70,
  "react-components-props": 65,
  "react-state-events": 70,
  "react-effects": 75,
  "react-hooks-in-depth": 80,
  "react-context-state": 75,
  "react-performance": 80,
  "react-data-fetching": 80,
  "react-patterns-production": 85,
  "nextjs-routing-layouts": 70,
  "nextjs-server-client-components": 75,
  "nextjs-data-fetching-streaming": 80,
  "nextjs-caching-rendering": 85,
  "nextjs-server-actions": 75,
  "nextjs-route-handlers": 70,
  "nextjs-error-loading": 65,
  "nextjs-metadata-seo": 60,
  "nextjs-optimization-production": 85,
  "frontend-testing": 80,
  "backend-frameworks-overview": 75,
  "node-runtime-modules": 70,
  "node-async-streams": 80,
  "node-express": 75,
  "node-middleware-errors": 70,
  "node-validation-security": 80,
  "node-auth": 75,
  "node-architecture": 80,
  "node-testing": 75,
  "node-production": 85,
  "nestjs-foundations": 85,
  "nestjs-providers-di": 80,
  "nestjs-pipes-guards-interceptors": 80,
  "nestjs-database": 75,
  "nestjs-auth": 80,
  "nestjs-testing-production": 80,
  "prisma-foundations": 80,
  "prisma-relations": 75,
  "prisma-queries": 80,
  "prisma-migrations": 70,
  "prisma-transactions-performance": 80,
  "rest-apis": 75,
  "graphql-basics": 70,
  "python-foundations": 60,
  "python-collections": 65,
  "python-iterators-generators": 70,
  "python-oop-typing": 75,
  "python-decorators-context-managers": 75,
  "python-advanced-typing": 80,
  "python-stdlib": 75,
  "python-fastapi": 80,
  "python-sqlalchemy": 85,
  "python-async-jobs": 85,
  "python-data-ai": 85,
  "python-performance": 80,
  "python-production": 85,
  "django-foundations": 65,
  "django-models-orm": 80,
  "django-views-urls": 70,
  "django-templates": 65,
  "django-forms-validation": 70,
  "django-admin": 60,
  "django-auth": 75,
  "django-drf-production": 85,
  "flask-foundations": 60,
  "flask-routing-templates": 65,
  "flask-forms-database": 75,
  "flask-blueprints-structure": 70,
  "flask-api-production": 75,
  "php-foundations": 60,
  "php-arrays-strings": 60,
  "php-functions-namespaces": 60,
  "php-oop": 75,
  "php-web-forms": 70,
  "php-database-pdo": 75,
  "php-composer-psr": 65,
  "php-security-production": 75,
  "laravel-foundations": 70,
  "laravel-routing-controllers": 70,
  "laravel-blade-views": 65,
  "laravel-eloquent": 85,
  "laravel-requests-validation": 70,
  "laravel-auth": 80,
  "laravel-api": 75,
  "laravel-testing-production": 80,
  "websockets-realtime": 75,
  "api-integrations": 70,
  "ai-llm-foundations": 55,
  "ai-llm-streaming": 50,
  "ai-llm-prompting": 55,
  "ai-llm-tool-use": 60,
  "ai-llm-rag": 65,
  "ai-llm-evaluation": 55,
  "ai-llm-production": 65,
  "architecture-monolith-microservices": 80,
  "db-relational-modeling": 75,
  "db-sql-queries": 80,
  "db-indexing-performance": 85,
  "db-transactions-acid": 80,
  "db-orm-n-plus-one": 80,
  "db-migrations-schema": 80,
  "db-scaling-replication": 85,
  "db-design-interview": 85,
  "nosql-foundations": 70,
  "nosql-document": 75,
  "nosql-key-value": 70,
  "nosql-wide-column": 75,
  "nosql-data-modeling": 80,
  "nosql-consistency-scaling": 80,
  "nosql-choosing-polyglot": 75,
  "redis-caching-sessions": 75,
  "db-engines-compared": 65,
  "authentication": 80,
  "web-security": 80,
  "linux-command-line": 55,
  "linux-server-ssh": 70,
  "linux-processes-logs-services": 70,
  "deployment": 75,
  "docker-ci-cd": 80,
  "observability": 75,
  "capstone": 120,
  "final-assessment": 60,
};

// A topic that is too big for one page (π.χ. Python, Node.js): groups several
// sub-lessons under a single heading inside a section.
export type LessonGroup = {
  id: string;
  title: string;
  description: string;
  lessons: Lesson[];
};

export type SectionItem = Lesson | LessonGroup;

export type CurriculumSection = {
  id: string;
  title: string;
  description: string;
  lessons: SectionItem[];
};

export function isLessonGroup(item: SectionItem): item is LessonGroup {
  return "lessons" in item;
}

// Όλα τα leaf lessons μιας ενότητας, "ισιωμένα" (groups ανοιγμένα), με τη σειρά τους.
export function flattenItems(items: SectionItem[]): Lesson[] {
  return items.flatMap((item) => (isLessonGroup(item) ? item.lessons : [item]));
}

export const curriculum: CurriculumSection[] = [
  {
    id: "web",
    title: "Web Foundations",
    description: "Πριν γράψεις κώδικα, καταλαβαίνεις τι συμβαίνει ανάμεσα σε browser και server.",
    lessons: [
      {
        id: "web-basics",
        title: "Τι είναι το Web;",
        description: "Internet, browser, server και request/response.",
        project: "Χάρτης client-server με δικά σου λόγια.",
        skills: ["Internet", "Browser", "Server"],
        href: "/lessons/web-basics",
      },
      {
        id: "how-the-web-works",
        title: "How the Web Really Works",
        description:
          "HTTP/HTTPS, TLS, DNS, CDN, caching headers, cookies και CORS — τι συμβαίνει πραγματικά από το URL μέχρι την απάντηση του server.",
        project: "Διάγραμμα ενός request: DNS → TLS → HTTP → response, με τα headers που μετράνε.",
        skills: ["HTTP", "DNS", "CORS"],
        href: "/lessons/how-the-web-works",
      },
    ],
  },
  {
    id: "html-css",
    title: "HTML & CSS",
    description: "Χτίζεις τη δομή, την προσβασιμότητα και το layout των πρώτων σου σελίδων.",
    lessons: [
      {
        id: "html-css",
        title: "HTML & CSS Basics",
        description: "Tags, απλή δομή σελίδας και πρώτες CSS αλλαγές.",
        project: "Προσωπική profile card.",
        skills: ["HTML tags", "CSS selectors", "Live preview"],
        href: "/lessons/html-css",
      },
      {
        id: "html-semantics",
        title: "HTML Structure & Semantics",
        description: "Semantic elements που δίνουν νόημα στη σελίδα.",
        project: "Semantic article page.",
        skills: ["header", "main", "section", "article"],
        href: "/lessons/html-semantics",
      },
      {
        id: "html-forms-accessibility",
        title: "HTML Forms & Accessibility",
        description: "Inputs, labels, buttons και βασική προσβασιμότητα.",
        project: "Accessible contact form.",
        skills: ["forms", "labels", "inputs"],
        href: "/lessons/html-forms-accessibility",
      },
      {
        id: "web-accessibility",
        title: "Accessibility (a11y)",
        description:
          "ARIA roles, keyboard navigation, focus management, WCAG και screen reader testing — πώς φτιάχνεις σελίδες που χρησιμοποιούν όλοι.",
        project: "Κάνε ένα interactive component (modal/menu) πλήρως προσβάσιμο.",
        skills: ["ARIA", "keyboard nav", "WCAG"],
        href: "/lessons/web-accessibility",
      },
      {
        id: "css-box-model",
        title: "CSS Box Model",
        description: "Margin, padding, border, width και σωστές αποστάσεις.",
        project: "Spacing card.",
        skills: ["box model", "padding", "margin", "border"],
        href: "/lessons/css-box-model",
      },
      {
        id: "css-flex-responsive",
        title: "CSS Flexbox & Responsive Layouts",
        description: "Flexbox, wrapping και responsive navigation.",
        project: "Responsive nav bar.",
        skills: ["flexbox", "gap", "wrap"],
        href: "/lessons/css-flex-responsive",
      },
      {
        id: "css-grid-layouts",
        title: "CSS Grid & Page Layouts",
        description: "Grid columns, card layouts, dashboard structure και responsive page layouts.",
        project: "Responsive dashboard grid.",
        skills: ["grid", "columns", "responsive"],
        href: "/lessons/css-grid-layouts",
      },
      {
        id: "css-modern-styling",
        title: "Styling at Scale",
        description:
          "Το πρόβλημα του CSS at scale και ο χάρτης των λύσεων: utility-first vs component-first, CSS Modules, design tokens και dark mode — πριν μπεις στα Tailwind/Bootstrap.",
        project: "Ξαναέντυσε ένα component με design tokens και dark mode.",
        skills: ["CSS Modules", "design tokens", "dark mode"],
        href: "/lessons/css-modern-styling",
      },
      {
        id: "tailwind",
        title: "Tailwind CSS",
        description:
          "Το κυρίαρχο utility-first framework, από τα foundations μέχρι production: λεξιλόγιο & κλίμακα, layout/responsive, states & dark mode, customization/theming και reuse — σε πλήρες βάθος.",
        lessons: [
          {
            id: "tailwind-foundations",
            title: "Tailwind Foundations",
            description: "Utility-first φιλοσοφία, setup/JIT, οι κατηγορίες utilities και η σταθερή κλίμακα spacing/colors.",
            project: "Ξαναέντυσε ένα κουμπί/κάρτα μόνο με utilities από την κλίμακα.",
            skills: ["utility-first", "scale", "JIT"],
            href: "/lessons/tailwind-foundations",
          },
          {
            id: "tailwind-layout-responsive",
            title: "Layout & Responsive",
            description: "Flexbox/grid utilities, mobile-first breakpoints και responsive layouts με prefixes (md:/lg:).",
            project: "Responsive grid layout που αλλάζει στήλες ανά breakpoint.",
            skills: ["flex/grid", "mobile-first", "breakpoints"],
            href: "/lessons/tailwind-layout-responsive",
          },
          {
            id: "tailwind-states-dark-mode",
            title: "States, Variants & Dark Mode",
            description: "hover/focus/active/disabled, group & peer variants, και dark mode με το dark: variant.",
            project: "Interactive component με states και λειτουργικό dark mode.",
            skills: ["state variants", "group/peer", "dark mode"],
            href: "/lessons/tailwind-states-dark-mode",
          },
          {
            id: "tailwind-customization",
            title: "Customization & Theming",
            description: "theme config, design tokens, arbitrary values [..], plugins και επέκταση της παλέτας/κλίμακας.",
            project: "Brand theme στο config και χρήση των tokens ως utilities.",
            skills: ["theme config", "tokens", "arbitrary values"],
            href: "/lessons/tailwind-customization",
          },
          {
            id: "tailwind-reuse-production",
            title: "Components, Reuse & Production",
            description: "Reuse με components vs @apply, αποφυγή επανάληψης, JIT/purge και μικρό production bundle.",
            project: "Μετέτρεψε επαναλαμβανόμενο markup σε reusable component.",
            skills: ["components", "@apply", "purge"],
            href: "/lessons/tailwind-reuse-production",
          },
        ],
      },
      {
        id: "bootstrap",
        title: "Bootstrap",
        description:
          "Το κυρίαρχο component-first framework, από τα foundations μέχρι customization: το 12-column grid, έτοιμα components, JavaScript components με data-bs-* και theming/accessibility — σε πλήρες βάθος.",
        lessons: [
          {
            id: "bootstrap-foundations",
            title: "Bootstrap Foundations",
            description: "Component-first φιλοσοφία, setup (CSS + JS bundle) και πρότυπο χρήσης με semantic component classes.",
            project: "Πρώτη σελίδα με buttons/alerts/badges από έτοιμες classes.",
            skills: ["component-first", "setup", "btn/card"],
            href: "/lessons/bootstrap-foundations",
          },
          {
            id: "bootstrap-grid-layout",
            title: "Grid System & Layout",
            description: "Το 12-column grid (container/row/col), responsive breakpoints, offsets, gutters και auto-layout.",
            project: "Responsive layout 3 στηλών που στοιβάζονται σε mobile.",
            skills: ["12-col grid", "breakpoints", "offsets"],
            href: "/lessons/bootstrap-grid-layout",
          },
          {
            id: "bootstrap-components",
            title: "Components",
            description: "Cards, navbar, forms, alerts, badges, list groups — η δομή markup των έτοιμων components.",
            project: "Card-based UI με navbar και validated form.",
            skills: ["cards", "forms", "navbar"],
            href: "/lessons/bootstrap-components",
          },
          {
            id: "bootstrap-javascript",
            title: "JavaScript Components",
            description: "Interactive components με data-bs-*: modal, dropdown, collapse, offcanvas, toast — χωρίς δικό σου JS.",
            project: "Modal + dropdown + collapsible section με data attributes.",
            skills: ["modal", "dropdown", "data-bs-*"],
            href: "/lessons/bootstrap-javascript",
          },
          {
            id: "bootstrap-customization-a11y",
            title: "Customization & Accessibility",
            description: "Theming με Sass variables και --bs-* CSS variables, αποφυγή 'generic look' και η built-in προσβασιμότητα.",
            project: "Customize το brand theme και έλεγξε keyboard/ARIA σε ένα component.",
            skills: ["Sass variables", "theming", "a11y"],
            href: "/lessons/bootstrap-customization-a11y",
          },
        ],
      },
    ],
  },
  {
    id: "javascript",
    title: "JavaScript",
    description: "Η βασική γλώσσα του fullstack path: fundamentals, DOM, async, runtime behavior και interview-level concepts.",
    lessons: [
      {
        id: "javascript-intro",
        title: "JavaScript Basics",
        description: "Variables, functions, events και πρώτη διαδραστικότητα.",
        project: "Interactive counter.",
        skills: ["variables", "functions", "events"],
        href: "/lessons/javascript-intro",
      },
      {
        id: "javascript-logic",
        title: "JavaScript Logic",
        description: "Conditions, loops και αποφάσεις στον κώδικα.",
        project: "Pass/fail score checker.",
        skills: ["if", "else", "loops"],
        href: "/lessons/javascript-logic",
      },
      {
        id: "javascript-arrays-objects",
        title: "JavaScript Arrays & Objects",
        description: "Λίστες δεδομένων, objects και rendering.",
        project: "Task list renderer.",
        skills: ["arrays", "objects", "map"],
        href: "/lessons/javascript-arrays-objects",
      },
      {
        id: "javascript-dom-forms",
        title: "JavaScript DOM, Forms & Storage",
        description: "DOM manipulation, submit events και localStorage.",
        project: "Saved notes form.",
        skills: ["DOM", "forms", "localStorage"],
        href: "/lessons/javascript-dom-forms",
      },
      {
        id: "javascript-scope-closures",
        title: "Scope, Hoisting & Closures",
        description: "Το πιο συχνό interview core: scope chains, lexical scope, hoisting και closures.",
        project: "Counter factory με closure.",
        skills: ["scope", "closures", "hoisting"],
        href: "/lessons/javascript-scope-closures",
      },
      {
        id: "javascript-this-prototypes",
        title: "this, Prototypes & Classes",
        description: "Πώς δουλεύουν το this, prototype chain, classes και object methods.",
        project: "Small user model with methods.",
        skills: ["this", "prototype", "class"],
        href: "/lessons/javascript-this-prototypes",
      },
      {
        id: "javascript-async-event-loop",
        title: "Async JavaScript & Event Loop",
        description: "Call stack, task queue, microtasks, promises, async/await και timers.",
        project: "Async timeline visualizer.",
        skills: ["event loop", "promises", "async/await"],
        href: "/lessons/javascript-async-event-loop",
      },
      {
        id: "javascript-fetch-errors",
        title: "Fetch, Errors & API Handling",
        description: "HTTP requests, try/catch, failed responses, retries και loading/error states.",
        project: "Robust API search widget.",
        skills: ["fetch", "try/catch", "error states"],
        href: "/lessons/javascript-fetch-errors",
      },
      {
        id: "javascript-modules-patterns",
        title: "Modules & Code Organization",
        description: "Imports/exports, pure functions, separation of concerns και μικρά reusable modules.",
        project: "Modular shopping cart logic.",
        skills: ["modules", "pure functions", "architecture"],
        href: "/lessons/javascript-modules-patterns",
      },
      {
        id: "javascript-interview-drills",
        title: "JavaScript Interview Drills",
        description: "Κλασικές ερωτήσεις: equality, coercion, closures, async output order και array methods.",
        project: "Interview question bank με εξηγήσεις.",
        skills: ["coercion", "output order", "array methods"],
        href: "/lessons/javascript-interview-drills",
      },
    ],
  },
  {
    id: "developer-workflow",
    title: "Developer Workflow",
    description: "Τα εργαλεία που χρειάζεσαι για να δουλεύεις σαν πραγματικός developer.",
    lessons: [
      {
        id: "linux-command-line",
        title: "Command Line Basics",
        description: "Terminal vs shell, navigation, χειρισμός αρχείων, pipes/redirection, exit codes και αλυσίδωση εντολών.",
        project: "Βρες το πιο πρόσφατο error ενός app μόνο μέσω terminal.",
        skills: ["shell", "pipes", "redirection"],
        href: "/lessons/linux-command-line",
      },
      {
        id: "git-github",
        title: "Git & GitHub",
        description: "Commits, branches, pull requests και συνεργασία σε κώδικα.",
        project: "Πρώτο repository με καθαρό README.",
        skills: ["commit", "branch", "pull request"],
        href: "/lessons/git-github",
      },
      {
        id: "agile-scrum-kanban",
        title: "Agile, Scrum & Kanban",
        description: "Πώς δουλεύουν tickets, boards, sprints, standups και acceptance criteria σε ομάδα.",
        project: "Kanban board για το capstone project.",
        skills: ["Scrum", "Kanban", "tickets"],
        href: "/lessons/agile-scrum-kanban",
      },
      {
        id: "job-ready-practice",
        title: "Job-Ready Practice & Portfolio",
        description: "Deliverables, acceptance criteria και portfolio tasks για να μετατρέψεις το roadmap σε job-ready έργα.",
        project: "Audit και portfolio plan για το capstone.",
        skills: ["portfolio", "acceptance criteria", "README"],
        href: "/lessons/job-ready-practice",
      },
      {
        id: "milestone-projects",
        title: "Milestone Projects",
        description: "Τέσσερα αυξανόμενα projects που αποδεικνύουν progression από HTML/CSS μέχρι fullstack.",
        project: "MILESTONES.md με acceptance criteria.",
        skills: ["projects", "rubrics", "portfolio"],
        href: "/lessons/milestone-projects",
      },
      {
        id: "code-review-practice",
        title: "Code Review Practice",
        description: "Πώς βρίσκεις bugs, security risks, missing validation και edge cases σε πραγματικό κώδικα.",
        project: "Self-review σε παλιό PR ή feature.",
        skills: ["review", "debugging", "quality"],
        href: "/lessons/code-review-practice",
      },
      {
        id: "typescript",
        title: "TypeScript",
        description:
          "Πλήρης διαδρομή για TypeScript σε βάθος συνέντευξης: από foundations & structural typing μέχρι unions/narrowing, functions, generics, utility/mapped types, type safety/config και declaration files.",
        lessons: [
          {
            id: "typescript-foundations",
            title: "TypeScript Foundations",
            description:
              "Structural typing, βασικοί τύποι & annotations, type vs interface, και type erasure (τα types εξαφανίζονται στη runtime).",
            project: "Typed domain model με interfaces και typed functions.",
            skills: ["structural typing", "type vs interface", "type erasure"],
            href: "/lessons/typescript-foundations",
          },
          {
            id: "typescript-unions-narrowing",
            title: "Unions, Narrowing & Type Guards",
            description:
              "Literal unions vs enum/as const, narrowing, discriminated unions με exhaustiveness/never, και custom type guards.",
            project: "Data-fetching states ως discriminated union που δεν σπάει.",
            skills: ["unions", "discriminated unions", "type guards"],
            href: "/lessons/typescript-unions-narrowing",
          },
          {
            id: "typescript-functions",
            title: "Typing Functions & Async",
            description:
              "Params (optional/default/rest), return types (void/never), function types, overloads, και async με Promise<T>/Awaited.",
            project: "Typed data layer με async functions και callbacks.",
            skills: ["function types", "overloads", "async types"],
            href: "/lessons/typescript-functions",
          },
          {
            id: "typescript-generics",
            title: "Generics, keyof & Indexed Access",
            description:
              "Generics & constraints, keyof, typeof type operator, indexed access T[K], και type-safe getProp pattern.",
            project: "Generic, type-safe utilities (getProp/pluck).",
            skills: ["generics", "keyof", "indexed access"],
            href: "/lessons/typescript-generics",
          },
          {
            id: "typescript-utility-types",
            title: "Utility, Mapped & Conditional Types",
            description:
              "Built-in utility types (Pick/Omit/Partial/Record/ReturnType), mapped & conditional types + infer, και ο satisfies operator.",
            project: "Παραγωγή συγγενικών types από ένα source of truth.",
            skills: ["utility types", "mapped/conditional", "satisfies"],
            href: "/lessons/typescript-utility-types",
          },
          {
            id: "typescript-safety-config",
            title: "Type Safety & tsconfig",
            description:
              "any vs unknown, assertions (as) & non-null !, runtime validation (Zod) για external data, και strict mode (tsconfig).",
            project: "Σκλήρυνση ενός data boundary: unknown + validation + strict.",
            skills: ["unknown", "runtime validation", "strict mode"],
            href: "/lessons/typescript-safety-config",
          },
          {
            id: "typescript-declarations",
            title: "Declaration Files & Type Ecosystem",
            description:
              ".d.ts declaration files, @types/DefinitelyTyped, ambient/global declarations, και module augmentation για library types.",
            project: "Project πλήρως typed με JS libraries, globals και augmentation.",
            skills: [".d.ts", "@types", "module augmentation"],
            href: "/lessons/typescript-declarations",
          },
        ],
      },
      {
        id: "testing-debugging",
        title: "Testing & Debugging",
        description: "Πώς βρίσκεις bugs και πώς γράφεις βασικά tests.",
        project: "Tested utility functions.",
        skills: ["debugger", "unit tests", "errors"],
        href: "/lessons/testing-debugging",
      },
      {
        id: "build-tools",
        title: "Build Tools: Vite & Webpack",
        description: "Τι κάνει ένας bundler, dev server/HMR, transpilation και Vite vs Webpack — πότε διαλέγεις τι.",
        project: "Στήσιμο project με Vite και κατανόηση του build output.",
        skills: ["Vite", "Webpack", "bundling"],
        href: "/lessons/build-tools",
      },
    ],
  },
  {
    id: "frontend-apps",
    title: "Frontend App Development",
    description: "Μετατρέπεις HTML/CSS/JS γνώση σε React εφαρμογές με TypeScript και production patterns.",
    lessons: [
      {
        id: "react",
        title: "React + TypeScript",
        description:
          "Από το rendering model μέχρι production: ένα πλήρες React mastery track με hooks, state management, performance, server state, patterns και testing — σε interview βάθος.",
        lessons: [
          {
            id: "react-rendering-model",
            title: "Rendering & Reconciliation",
            description: "UI = f(state), re-renders, virtual DOM diffing, keys και γιατί το reference equality έχει σημασία.",
            project: "Visualizer που δείχνει πότε και γιατί ξανα-renderάρει κάθε component.",
            skills: ["re-render", "reconciliation", "keys"],
            href: "/lessons/react-rendering-model",
          },
          {
            id: "react-components-props",
            title: "Components, Props & Composition",
            description: "Typed props contracts, children, composition vs configuration και one-way data flow.",
            project: "Reusable component library με typed props και composition.",
            skills: ["props", "composition", "children"],
            href: "/lessons/react-components-props",
          },
          {
            id: "react-state-events",
            title: "State, Events & Forms",
            description: "useState, immutable updates, functional updates, controlled inputs και event handling.",
            project: "Controlled form με typed state και validation.",
            skills: ["useState", "controlled inputs", "immutability"],
            href: "/lessons/react-state-events",
          },
          {
            id: "react-effects",
            title: "Effects & Lifecycle",
            description: "useEffect, cleanup, dependency array, race conditions και πότε ΔΕΝ χρειάζεσαι effect.",
            project: "Data loader με AbortController, cleanup και loading/error states.",
            skills: ["useEffect", "cleanup", "race conditions"],
            href: "/lessons/react-effects",
          },
          {
            id: "react-hooks-in-depth",
            title: "Hooks in Depth",
            description: "useRef, useReducer, useMemo, useCallback, custom hooks και οι κανόνες των hooks.",
            project: "Custom hooks (useToggle, useDebounce, useFetch) και reducer-based state.",
            skills: ["useReducer", "custom hooks", "useRef"],
            href: "/lessons/react-hooks-in-depth",
          },
          {
            id: "react-context-state",
            title: "Context & State Management",
            description: "Context, prop drilling, re-render traps και πότε φεύγεις σε external store (Zustand/Redux).",
            project: "Theme + auth context χωρίς περιττά re-renders.",
            skills: ["Context", "prop drilling", "state management"],
            href: "/lessons/react-context-state",
          },
          {
            id: "react-performance",
            title: "Performance & Optimization",
            description: "React.memo, useMemo/useCallback, re-render causes, profiling και list virtualization.",
            project: "Profile & βελτιστοποίηση αργής λίστας με μετρήσιμη διαφορά.",
            skills: ["memo", "profiling", "virtualization"],
            href: "/lessons/react-performance",
          },
          {
            id: "react-data-fetching",
            title: "Data Fetching & Server State",
            description: "Server state vs UI state, React Query/SWR, caching, Suspense και error boundaries.",
            project: "Data layer με caching, retries και error boundary.",
            skills: ["React Query", "caching", "Suspense"],
            href: "/lessons/react-data-fetching",
          },
          {
            id: "react-patterns-production",
            title: "Patterns, Testing & Production",
            description: "Composition patterns, error boundaries, accessibility και testing με React Testing Library.",
            project: "Tested, accessible feature με σωστά patterns.",
            skills: ["patterns", "testing", "accessibility"],
            href: "/lessons/react-patterns-production",
          },
        ],
      },
      {
        id: "nextjs",
        title: "Next.js (App Router)",
        description:
          "Από το file-system routing μέχρι production: ένα πλήρες Next.js 16 mastery track με Server/Client Components, streaming, Cache Components, Server Actions, route handlers, metadata και deployment.",
        lessons: [
          {
            id: "nextjs-routing-layouts",
            title: "App Router & File-System Routing",
            description: "page/layout, nested routes, dynamic segments [slug], params/searchParams ως Promises και Link.",
            project: "Multi-page app με nested layouts και dynamic routes.",
            skills: ["routing", "layouts", "dynamic segments"],
            href: "/lessons/nextjs-routing-layouts",
          },
          {
            id: "nextjs-server-client-components",
            title: "Server & Client Components",
            description: "RSC by default, το 'use client' boundary, πότε διαλέγεις το καθένα και interleaving.",
            project: "Server page με νησίδες client interactivity.",
            skills: ["RSC", "use client", "boundaries"],
            href: "/lessons/nextjs-server-client-components",
          },
          {
            id: "nextjs-data-fetching-streaming",
            title: "Data Fetching & Streaming",
            description: "async Server Components, fetch χωρίς default cache, Suspense, loading.js και parallel vs sequential.",
            project: "Σελίδα με streaming και parallel data loading.",
            skills: ["async components", "Suspense", "streaming"],
            href: "/lessons/nextjs-data-fetching-streaming",
          },
          {
            id: "nextjs-caching-rendering",
            title: "Caching & Rendering Strategies",
            description: "Cache Components/PPR, use cache, cacheLife/cacheTag, static shell και runtime APIs (cookies/headers).",
            project: "Σελίδα που συνδυάζει static, cached και request-time περιεχόμενο.",
            skills: ["use cache", "PPR", "cacheLife"],
            href: "/lessons/nextjs-caching-rendering",
          },
          {
            id: "nextjs-server-actions",
            title: "Server Actions & Mutations",
            description: "use server, forms, useActionState, revalidatePath/Tag, redirect και pending states.",
            project: "Form mutation με validation, revalidation και redirect.",
            skills: ["Server Actions", "useActionState", "revalidate"],
            href: "/lessons/nextjs-server-actions",
          },
          {
            id: "nextjs-route-handlers",
            title: "Route Handlers & APIs",
            description: "route.ts, HTTP methods, Web Request/Response, NextRequest/NextResponse και RouteContext typing.",
            project: "REST endpoints με route handlers και typed context.",
            skills: ["route.ts", "NextResponse", "HTTP methods"],
            href: "/lessons/nextjs-route-handlers",
          },
          {
            id: "nextjs-error-loading",
            title: "Error & Loading UI",
            description: "error.tsx (unstable_retry), not-found, global-error και expected vs uncaught errors.",
            project: "Route με error boundaries, not-found και loading states.",
            skills: ["error.tsx", "notFound", "loading"],
            href: "/lessons/nextjs-error-loading",
          },
          {
            id: "nextjs-metadata-seo",
            title: "Metadata, SEO & OG Images",
            description: "Metadata object, generateMetadata, ImageResponse (next/og), sitemap/robots και streaming metadata.",
            project: "SEO-ready σελίδες με dynamic OG images.",
            skills: ["generateMetadata", "ImageResponse", "SEO"],
            href: "/lessons/nextjs-metadata-seo",
          },
          {
            id: "nextjs-optimization-production",
            title: "Optimization & Production",
            description: "next/image, next/font, Proxy (πρώην Middleware), env vars/NEXT_PUBLIC και deployment.",
            project: "Production build με optimized images, fonts και proxy.",
            skills: ["next/image", "Proxy", "deployment"],
            href: "/lessons/nextjs-optimization-production",
          },
        ],
      },
      {
        id: "frontend-testing",
        title: "React Testing",
        description: "Component tests, user flows και βασική κάλυψη με React Testing Library ή Playwright.",
        project: "Tested form and todo interactions.",
        skills: ["RTL", "Playwright", "user flows"],
        href: "/lessons/frontend-testing",
      },
    ],
  },
  {
    id: "backend-apis",
    title: "Backend & APIs",
    description: "Φτιάχνεις server-side λογική και endpoints που μιλάνε με το frontend.",
    lessons: [
      {
        id: "backend-frameworks-overview",
        title: "Backend Frameworks: The Shared Mental Model",
        description:
          "Το κοινό μοντέλο πίσω από Express, NestJS, Django, Flask, FastAPI και Laravel: routing, request lifecycle, middleware, ORM, validation, auth — και πότε διαλέγεις micro vs full-stack.",
        project: "Comparison map: το ίδιο concept (routing/middleware/ORM) σε όλα τα frameworks.",
        skills: ["routing", "middleware", "MVC vs layered"],
        href: "/lessons/backend-frameworks-overview",
      },
      {
        id: "node",
        title: "Node.js & Express",
        description:
          "Το runtime, το async μοντέλο και το Express web framework — από foundations μέχρι production-ready REST APIs με auth, testing και scaling.",
        lessons: [
          {
            id: "node-runtime-modules",
            title: "Node Runtime & Modules",
            description: "V8, libuv, event loop, single-threaded non-blocking I/O, CommonJS vs ESM, process & env.",
            project: "Πειράματα event loop ordering και ESM setup.",
            skills: ["event loop", "non-blocking I/O", "ESM"],
            href: "/lessons/node-runtime-modules",
          },
          {
            id: "node-async-streams",
            title: "Async Patterns & Streams",
            description: "callbacks→promises→async/await, Promise.all/allSettled, EventEmitter και streams/backpressure.",
            project: "Παράλληλα API calls και stream pipeline για μεγάλο αρχείο.",
            skills: ["async/await", "Promise.all", "streams"],
            href: "/lessons/node-async-streams",
          },
          {
            id: "node-express",
            title: "Express Fundamentals",
            description: "Routing, req/res lifecycle, status codes, routers και λεπτοί handlers.",
            project: "CRUD tasks API με σωστά status codes.",
            skills: ["Express", "routing", "status codes"],
            href: "/lessons/node-express",
          },
          {
            id: "node-middleware-errors",
            title: "Middleware & Error Handling",
            description: "Middleware pipeline, centralized error handler και το async error trap.",
            project: "Production-grade error handling χωρίς κρεμασμένα requests.",
            skills: ["middleware", "error handler", "async errors"],
            href: "/lessons/node-middleware-errors",
          },
          {
            id: "node-validation-security",
            title: "Validation & Security",
            description: "Zod schema validation, helmet/CORS/rate limit, injection, secrets και password hashing.",
            project: "Ασφάλιση API με validation και security controls.",
            skills: ["Zod", "security", "bcrypt"],
            href: "/lessons/node-validation-security",
          },
          {
            id: "node-auth",
            title: "Authentication & Sessions",
            description: "Sessions vs JWT, cookies, password hashing, refresh tokens και route protection με middleware.",
            project: "Auth flow με login, protected routes και refresh tokens.",
            skills: ["JWT", "sessions", "cookies"],
            href: "/lessons/node-auth",
          },
          {
            id: "node-architecture",
            title: "Layered Architecture",
            description: "routes/services/repositories, validated config και dependency injection.",
            project: "Refactor fat controller σε καθαρά στρώματα.",
            skills: ["layering", "config", "DI"],
            href: "/lessons/node-architecture",
          },
          {
            id: "node-testing",
            title: "Testing Node APIs",
            description: "Unit tests (Jest/Vitest), integration με Supertest, mocking και testing pyramid.",
            project: "Test suite με unit + integration και error paths.",
            skills: ["Vitest", "Supertest", "mocking"],
            href: "/lessons/node-testing",
          },
          {
            id: "node-production",
            title: "Performance, Scaling & Production",
            description: "cluster/horizontal scaling, worker_threads, Redis caching, graceful shutdown και observability.",
            project: "Production-ready service με caching, shutdown και logging.",
            skills: ["scaling", "caching", "observability"],
            href: "/lessons/node-production",
          },
        ],
      },
      {
        id: "nestjs",
        title: "NestJS",
        description:
          "Το opinionated, TypeScript-first framework: modules, dependency injection, το request pipeline και production patterns — η δομή που ζητούν enterprise codebases.",
        lessons: [
          {
            id: "nestjs-foundations",
            title: "NestJS Foundations",
            description: "Modules, controllers, providers και dependency injection — η αρχιτεκτονική του Nest.",
            project: "Feature module με controller, service και DI.",
            skills: ["modules", "controllers", "DI"],
            href: "/lessons/nestjs-foundations",
          },
          {
            id: "nestjs-providers-di",
            title: "Providers & Dependency Injection",
            description: "Custom providers, injection scopes, dynamic modules και ConfigModule για typed config.",
            project: "Dynamic module με typed config και injected service.",
            skills: ["providers", "DI scopes", "dynamic modules"],
            href: "/lessons/nestjs-providers-di",
          },
          {
            id: "nestjs-pipes-guards-interceptors",
            title: "Pipes, Guards & Interceptors",
            description: "Το request pipeline: ValidationPipe, guards για authorization, interceptors και exception filters.",
            project: "Validation pipe + guard + logging interceptor σε ένα module.",
            skills: ["ValidationPipe", "guards", "interceptors"],
            href: "/lessons/nestjs-pipes-guards-interceptors",
          },
          {
            id: "nestjs-database",
            title: "Database with Prisma",
            description: "Injectable PrismaService, repository pattern και καθαρό data access ανά module.",
            project: "PrismaService module με CRUD resource.",
            skills: ["Prisma", "repository", "modules"],
            href: "/lessons/nestjs-database",
          },
          {
            id: "nestjs-auth",
            title: "Authentication & Authorization",
            description: "Passport strategies, JWT, AuthGuard και role-based access control με custom decorators.",
            project: "JWT auth με login, protected routes και roles.",
            skills: ["Passport", "JWT", "RBAC"],
            href: "/lessons/nestjs-auth",
          },
          {
            id: "nestjs-testing-production",
            title: "Testing & Production",
            description: "Testing module, unit + e2e με Supertest, config validation και deployment.",
            project: "Unit + e2e suite για feature module.",
            skills: ["Test module", "e2e", "config"],
            href: "/lessons/nestjs-testing-production",
          },
        ],
      },
      {
        id: "prisma",
        title: "Prisma",
        description:
          "Type-safe ORM για Node/TypeScript: schema-first μοντέλο, relations, migrations και performance — το data layer που δουλεύει με Express, NestJS και Next.js.",
        lessons: [
          {
            id: "prisma-foundations",
            title: "Prisma Foundations",
            description: "Schema, datasource, generated client και type-safe CRUD.",
            project: "Data layer με schema και type-safe CRUD.",
            skills: ["schema", "Prisma Client", "CRUD"],
            href: "/lessons/prisma-foundations",
          },
          {
            id: "prisma-relations",
            title: "Relations & Nested Writes",
            description: "1-1, 1-n, m-n relations, nested writes, include vs select και relation filtering.",
            project: "Σχεσιακό μοντέλο με nested create και filtered includes.",
            skills: ["relations", "nested writes", "include/select"],
            href: "/lessons/prisma-relations",
          },
          {
            id: "prisma-queries",
            title: "Queries, Filtering & Pagination",
            description: "where/orderBy, cursor vs offset pagination, aggregations, groupBy και raw queries.",
            project: "Listing endpoint με filtering, sorting και cursor pagination.",
            skills: ["filtering", "pagination", "aggregations"],
            href: "/lessons/prisma-queries",
          },
          {
            id: "prisma-migrations",
            title: "Migrations & Seeding",
            description: "migrate dev vs deploy, schema evolution, drift, seeding και shadow database.",
            project: "Migration workflow με seed script.",
            skills: ["migrations", "seeding", "schema drift"],
            href: "/lessons/prisma-migrations",
          },
          {
            id: "prisma-transactions-performance",
            title: "Transactions & Performance",
            description: "Interactive transactions, το N+1 problem, connection pooling και indexing.",
            project: "Transaction-safe operation χωρίς N+1.",
            skills: ["transactions", "N+1", "pooling"],
            href: "/lessons/prisma-transactions-performance",
          },
        ],
      },
      {
        id: "rest-apis",
        title: "REST APIs",
        description: "HTTP methods, status codes, request/response και API contracts.",
        project: "CRUD API contract.",
        skills: ["GET", "POST", "status codes"],
        href: "/lessons/rest-apis",
      },
      {
        id: "graphql-basics",
        title: "GraphQL Basics",
        description: "Queries, mutations και πότε έχει νόημα σε σχέση με REST.",
        project: "Simple GraphQL schema.",
        skills: ["schema", "queries", "mutations"],
        href: "/lessons/graphql-basics",
      },
      {
        id: "python",
        title: "Python",
        description:
          "Από τα foundations μέχρι production FastAPI services: μια πλήρης διαδρομή για AI/data/background-job services δίπλα στο main app.",
        lessons: [
          {
            id: "python-foundations",
            title: "Python Foundations",
            description: "Syntax, dynamic+strong typing, truthiness, functions και Pythonic idioms vs JavaScript.",
            project: "Μετατροπή JavaScript-style λογικής σε Pythonic κώδικα.",
            skills: ["syntax", "typing model", "functions"],
            href: "/lessons/python-foundations",
          },
          {
            id: "python-collections",
            title: "Collections & Comprehensions",
            description: "list/dict/set/tuple, comprehensions, slicing, unpacking και generators.",
            project: "Pythonic data wrangling πάνω σε λίστα από records.",
            skills: ["comprehensions", "generators", "slicing"],
            href: "/lessons/python-collections",
          },
          {
            id: "python-iterators-generators",
            title: "Iterators, Generators & Lazy Evaluation",
            description: "Iteration protocol, generators, yield from, lazy pipelines και itertools.",
            project: "Lazy data pipeline που επεξεργάζεται 'τεράστιο' αρχείο με σταθερή μνήμη.",
            skills: ["iterators", "generators", "itertools"],
            href: "/lessons/python-iterators-generators",
          },
          {
            id: "python-oop-typing",
            title: "OOP, Type Hints & Dataclasses",
            description: "Classes, self, dunder methods, type hints, mypy και @dataclass.",
            project: "Typed domain model με dataclasses.",
            skills: ["classes", "type hints", "dataclasses"],
            href: "/lessons/python-oop-typing",
          },
          {
            id: "python-decorators-context-managers",
            title: "Decorators & Context Managers",
            description: "Decorators (με/χωρίς params, functools.wraps), closures applied και context managers.",
            project: "Reusable decorators (timing/retry/cache) και transaction context manager.",
            skills: ["decorators", "functools.wraps", "with"],
            href: "/lessons/python-decorators-context-managers",
          },
          {
            id: "python-advanced-typing",
            title: "Advanced Typing",
            description: "Generics (TypeVar), Protocol, type narrowing, Literal/TypedDict και mypy --strict.",
            project: "Generic, typed utility module που περνά mypy --strict.",
            skills: ["generics", "Protocol", "mypy"],
            href: "/lessons/python-advanced-typing",
          },
          {
            id: "python-stdlib",
            title: "Standard Library Mastery",
            description: "collections, functools, itertools, pathlib και timezone-aware datetime.",
            project: "Λύση κλασικών data προβλημάτων μόνο με stdlib.",
            skills: ["collections", "functools", "pathlib"],
            href: "/lessons/python-stdlib",
          },
          {
            id: "python-fastapi",
            title: "FastAPI Services",
            description: "Endpoints, Pydantic validation, dependency injection και contract με το main app.",
            project: "Python service που δέχεται job και επιστρέφει result.",
            skills: ["FastAPI", "Pydantic", "Depends"],
            href: "/lessons/python-fastapi",
          },
          {
            id: "python-sqlalchemy",
            title: "Databases with SQLAlchemy & Alembic",
            description: "Typed ORM models, select()/Session CRUD, relationships, N+1 problem, transactions, migrations.",
            project: "Data layer με relationships χωρίς N+1 και Alembic migration.",
            skills: ["SQLAlchemy", "N+1", "Alembic"],
            href: "/lessons/python-sqlalchemy",
          },
          {
            id: "python-async-jobs",
            title: "Async, Concurrency & Background Jobs",
            description: "GIL, asyncio vs threads vs processes, queue + worker, retries και status flow.",
            project: "Background job pipeline με queue, worker και status.",
            skills: ["GIL", "asyncio", "Celery"],
            href: "/lessons/python-async-jobs",
          },
          {
            id: "python-data-ai",
            title: "Data & AI with Python",
            description: "numpy/pandas vectorization, data wrangling, model serving και production AI/LLM patterns.",
            project: "Service που κάνει vectorized data processing και σερβίρει predictions.",
            skills: ["numpy", "pandas", "model serving"],
            href: "/lessons/python-data-ai",
          },
          {
            id: "python-performance",
            title: "Performance & Profiling",
            description: "timeit/cProfile, Big-O δομών, performance traps, caching και πότε φεύγεις από pure Python.",
            project: "Profile & βελτιστοποίηση αργού script με μετρήσεις.",
            skills: ["cProfile", "Big-O", "caching"],
            href: "/lessons/python-performance",
          },
          {
            id: "python-production",
            title: "Testing, Packaging & Production",
            description: "pytest, fixtures/mocking, virtual environments, packaging, Docker και config από env.",
            project: "Tested, containerized FastAPI service με health check.",
            skills: ["pytest", "venv", "deployment"],
            href: "/lessons/python-production",
          },
        ],
      },
      {
        id: "django",
        title: "Django",
        description:
          "Το 'batteries-included' Python framework: MVT, ORM, migrations, templates, forms, το ξακουστό admin, auth και REST APIs με DRF — σε production βάθος.",
        lessons: [
          {
            id: "django-foundations",
            title: "Django Foundations & MVT",
            description: "MVT architecture, project vs app, settings, manage.py και το request lifecycle.",
            project: "Setup project και πρώτη ροή URL → view → template.",
            skills: ["MVT", "manage.py", "settings"],
            href: "/lessons/django-foundations",
          },
          {
            id: "django-models-orm",
            title: "Models, ORM & Migrations",
            description: "Models, migrations, QuerySets, relationships, N+1 και select_related/prefetch_related.",
            project: "Data layer με relationships χωρίς N+1.",
            skills: ["ORM", "migrations", "QuerySet"],
            href: "/lessons/django-models-orm",
          },
          {
            id: "django-views-urls",
            title: "Views & URL Routing",
            description: "Function & class-based views, URLconf, route params και request/response.",
            project: "CRUD views με URL routing.",
            skills: ["views", "URLconf", "CBV"],
            href: "/lessons/django-views-urls",
          },
          {
            id: "django-templates",
            title: "Templates & Static Files",
            description: "Django template language, inheritance, context, filters και static/media files.",
            project: "Reusable layout με template inheritance.",
            skills: ["templates", "inheritance", "static"],
            href: "/lessons/django-templates",
          },
          {
            id: "django-forms-validation",
            title: "Forms & Validation",
            description: "Forms, ModelForms, validation, CSRF και error handling.",
            project: "Validated ModelForm για δημιουργία εγγραφής.",
            skills: ["forms", "ModelForm", "CSRF"],
            href: "/lessons/django-forms-validation",
          },
          {
            id: "django-admin",
            title: "The Django Admin",
            description: "Το auto-generated admin site, registration, customization και γιατί ξεχωρίζει το Django.",
            project: "Customized admin για διαχείριση περιεχομένου.",
            skills: ["admin", "ModelAdmin", "CRUD"],
            href: "/lessons/django-admin",
          },
          {
            id: "django-auth",
            title: "Authentication & Permissions",
            description: "Το auth system, login/logout, permissions, groups και προστασία views.",
            project: "Protected area με permissions.",
            skills: ["auth", "permissions", "login_required"],
            href: "/lessons/django-auth",
          },
          {
            id: "django-drf-production",
            title: "REST APIs (DRF) & Production",
            description: "Django REST Framework: serializers, viewsets, auth· settings split και deployment.",
            project: "REST API με DRF serializers και token auth.",
            skills: ["DRF", "serializers", "deployment"],
            href: "/lessons/django-drf-production",
          },
        ],
      },
      {
        id: "flask",
        title: "Flask",
        description:
          "Το minimal Python micro-framework: routes, Jinja2 templates, forms, βάση με SQLAlchemy, blueprints/app factory και JSON APIs — ευελιξία αντί για conventions.",
        lessons: [
          {
            id: "flask-foundations",
            title: "Flask Foundations",
            description: "Micro-framework φιλοσοφία, app, routes, request/response και debug mode.",
            project: "Πρώτη Flask εφαρμογή με routes.",
            skills: ["Flask", "routes", "request"],
            href: "/lessons/flask-foundations",
          },
          {
            id: "flask-routing-templates",
            title: "Routing & Jinja2 Templates",
            description: "Dynamic routes, HTTP methods, Jinja2 templates, inheritance και static files.",
            project: "Σελίδες με dynamic routes και template inheritance.",
            skills: ["routing", "Jinja2", "templates"],
            href: "/lessons/flask-routing-templates",
          },
          {
            id: "flask-forms-database",
            title: "Forms & Database",
            description: "Forms & validation, Flask-SQLAlchemy models, CRUD και sessions.",
            project: "CRUD app με Flask-SQLAlchemy.",
            skills: ["forms", "SQLAlchemy", "CRUD"],
            href: "/lessons/flask-forms-database",
          },
          {
            id: "flask-blueprints-structure",
            title: "Blueprints & App Factory",
            description: "Blueprints, application factory pattern, extensions και δομή για μεγαλύτερα apps.",
            project: "Refactor σε blueprints με app factory.",
            skills: ["blueprints", "app factory", "structure"],
            href: "/lessons/flask-blueprints-structure",
          },
          {
            id: "flask-api-production",
            title: "JSON APIs & Production",
            description: "JSON APIs, error handlers, config classes, environment και deployment με gunicorn.",
            project: "REST API με σωστά status codes και config.",
            skills: ["JSON API", "config", "gunicorn"],
            href: "/lessons/flask-api-production",
          },
        ],
      },
      {
        id: "php",
        title: "PHP",
        description:
          "Από τη γλώσσα μέχρι production: modern PHP 8, OOP, web requests, βάσεις με PDO, Composer και ασφάλεια — η βάση πριν περάσεις στο Laravel.",
        lessons: [
          {
            id: "php-foundations",
            title: "PHP Foundations",
            description: "Syntax, τύποι, variables, control flow και modern PHP 8 features (typed, strict).",
            project: "CLI script που επεξεργάζεται και αναφέρει δεδομένα.",
            skills: ["syntax", "types", "PHP 8"],
            href: "/lessons/php-foundations",
          },
          {
            id: "php-arrays-strings",
            title: "Arrays & Strings",
            description: "Indexed/associative arrays, array functions, string manipulation και formatting.",
            project: "Data formatter πάνω σε λίστα από records.",
            skills: ["arrays", "array functions", "strings"],
            href: "/lessons/php-arrays-strings",
          },
          {
            id: "php-functions-namespaces",
            title: "Functions, Includes & Namespaces",
            description: "Functions, arrow functions, include/require και code organization με namespaces.",
            project: "Modular helper library με namespaces.",
            skills: ["functions", "namespaces", "includes"],
            href: "/lessons/php-functions-namespaces",
          },
          {
            id: "php-oop",
            title: "OOP in PHP",
            description: "Classes, visibility, interfaces, traits, abstract, enums και readonly properties.",
            project: "Typed domain model με interfaces και traits.",
            skills: ["classes", "interfaces", "traits"],
            href: "/lessons/php-oop",
          },
          {
            id: "php-web-forms",
            title: "Web Requests, Forms & Sessions",
            description: "Request lifecycle, superglobals, forms, cookies και sessions χωρίς framework.",
            project: "Login flow με sessions σε καθαρή PHP.",
            skills: ["superglobals", "forms", "sessions"],
            href: "/lessons/php-web-forms",
          },
          {
            id: "php-database-pdo",
            title: "Databases with PDO",
            description: "PDO, prepared statements, SQL injection prevention, fetch modes και transactions.",
            project: "CRUD με PDO και prepared statements.",
            skills: ["PDO", "prepared statements", "transactions"],
            href: "/lessons/php-database-pdo",
          },
          {
            id: "php-composer-psr",
            title: "Composer, Autoloading & Errors",
            description: "Composer, PSR-4 autoloading, packages, PSR standards και exception handling.",
            project: "Project με Composer, autoloading και centralized errors.",
            skills: ["Composer", "PSR-4", "exceptions"],
            href: "/lessons/php-composer-psr",
          },
          {
            id: "php-security-production",
            title: "Security & Production",
            description: "Validation, password hashing, XSS/CSRF, env config και deployment basics.",
            project: "Ασφαλισμένη PHP εφαρμογή έτοιμη για deploy.",
            skills: ["password_hash", "CSRF", "deployment"],
            href: "/lessons/php-security-production",
          },
        ],
      },
      {
        id: "laravel",
        title: "Laravel",
        description:
          "Το πιο δημοφιλές PHP framework: MVC, routing, Eloquent ORM, Blade, validation, auth, APIs και testing — σε production βάθος.",
        lessons: [
          {
            id: "laravel-foundations",
            title: "Laravel Foundations & MVC",
            description: "MVC, project structure, artisan, request lifecycle και service container/DI.",
            project: "Setup project και πρώτη ροή route → controller → view.",
            skills: ["MVC", "artisan", "container"],
            href: "/lessons/laravel-foundations",
          },
          {
            id: "laravel-routing-controllers",
            title: "Routing, Controllers & Middleware",
            description: "Routes, params, resource controllers, middleware και route model binding.",
            project: "RESTful routes με controllers και middleware.",
            skills: ["routing", "controllers", "middleware"],
            href: "/lessons/laravel-routing-controllers",
          },
          {
            id: "laravel-blade-views",
            title: "Blade Templates & Views",
            description: "Blade syntax, layouts, components, slots, partials και escaping.",
            project: "Reusable layout με Blade components.",
            skills: ["Blade", "components", "layouts"],
            href: "/lessons/laravel-blade-views",
          },
          {
            id: "laravel-eloquent",
            title: "Eloquent ORM & Migrations",
            description: "Models, migrations, relationships, N+1 problem, eager loading και query builder.",
            project: "Data layer με relationships χωρίς N+1.",
            skills: ["Eloquent", "migrations", "relationships"],
            href: "/lessons/laravel-eloquent",
          },
          {
            id: "laravel-requests-validation",
            title: "Requests, Validation & Sessions",
            description: "Form requests, validation rules, error bags, CSRF, sessions και flash messages.",
            project: "Validated form με Form Request class.",
            skills: ["validation", "Form Request", "CSRF"],
            href: "/lessons/laravel-requests-validation",
          },
          {
            id: "laravel-auth",
            title: "Authentication & Authorization",
            description: "Auth scaffolding, guards, hashing, gates, policies και Sanctum.",
            project: "Protected area με gates και policies.",
            skills: ["auth", "policies", "Sanctum"],
            href: "/lessons/laravel-auth",
          },
          {
            id: "laravel-api",
            title: "Building APIs",
            description: "API routes, API Resources, JSON responses, token auth με Sanctum και versioning.",
            project: "REST API με resources και token authentication.",
            skills: ["API resources", "Sanctum", "JSON"],
            href: "/lessons/laravel-api",
          },
          {
            id: "laravel-testing-production",
            title: "Testing, Queues & Production",
            description: "Feature/unit tests (Pest/PHPUnit), queues & jobs, caching και deployment.",
            project: "Tested feature με background queue job.",
            skills: ["Pest", "queues", "deployment"],
            href: "/lessons/laravel-testing-production",
          },
        ],
      },
      {
        id: "websockets-realtime",
        title: "WebSockets & Real-Time Apps",
        description: "Persistent connections για chat, notifications, live dashboards και status updates.",
        project: "Real-time notifications ή live chat flow.",
        skills: ["WebSocket", "Socket.IO", "Redis Pub/Sub"],
        href: "/lessons/websockets-realtime",
      },
      {
        id: "api-integrations",
        title: "API Integrations",
        description: "Σύνδεση με τρίτα APIs, auth headers, retries, rate limits και error handling.",
        project: "External API dashboard.",
        skills: ["fetch", "auth headers", "rate limits"],
        href: "/lessons/api-integrations",
      },
      {
        id: "ai-llm",
        title: "AI & LLM Integration",
        description:
          "Πλήρης διαδρομή για production AI features σε fullstack app: από την πρώτη ασφαλή κλήση μέχρι streaming, prompting, tool use/agents, RAG, evaluation και production (cost/observability/security).",
        lessons: [
          {
            id: "ai-llm-foundations",
            title: "AI & LLM Foundations",
            description:
              "Το LLM ως stateless metered API: key στο backend, πρώτη κλήση, ιστορικό messages, επιλογή μοντέλου.",
            project: "Ασφαλές backend endpoint που καλεί LLM με multi-turn ιστορικό.",
            skills: ["LLM API", "stateless", "model choice"],
            href: "/lessons/ai-llm-foundations",
          },
          {
            id: "ai-llm-streaming",
            title: "Streaming responses στο UI",
            description:
              "End-to-end streaming: LLM events → ReadableStream στο route handler → reader + state στο React.",
            project: "Streaming chat UI με σταδιακή εμφάνιση απάντησης.",
            skills: ["streaming", "ReadableStream", "SSE"],
            href: "/lessons/ai-llm-streaming",
          },
          {
            id: "ai-llm-prompting",
            title: "Prompt design & Structured outputs",
            description:
              "System vs user prompt, αρχές prompt design, και εγγυημένα έγκυρο JSON με output_config.format (schema + enum).",
            project: "Endpoint extraction που επιστρέφει δομημένο, έγκυρο JSON.",
            skills: ["system prompt", "structured output", "JSON schema"],
            href: "/lessons/ai-llm-prompting",
          },
          {
            id: "ai-llm-tool-use",
            title: "Tool use & Agents",
            description:
              "Function calling: ο κύκλος tool_use, ποιος εκτελεί, ο agent loop, και τα όρια ασφαλείας (validation/confirmation).",
            project: "Agent loop με ένα ασφαλές tool και confirmation σε επικίνδυνη ενέργεια.",
            skills: ["tool use", "agents", "function calling"],
            href: "/lessons/ai-llm-tool-use",
          },
          {
            id: "ai-llm-rag",
            title: "RAG & Vector Search",
            description:
              "Grounding σε δικά σου δεδομένα: embeddings, vector search, chunking, και RAG vs fine-tuning.",
            project: "RAG flow: index offline, retrieve + answer με πηγές.",
            skills: ["RAG", "embeddings", "vector DB"],
            href: "/lessons/ai-llm-rag",
          },
          {
            id: "ai-llm-evaluation",
            title: "Evaluation & Testing",
            description:
              "Πώς μετράς ποιότητα σε μη ντετερμινιστικό feature: eval datasets, graders, LLM-as-judge, baseline & regressions.",
            project: "Eval με dataset + scoring που αποφασίζει αν μια αλλαγή βελτιώνει το feature.",
            skills: ["evals", "LLM-as-judge", "regression"],
            href: "/lessons/ai-llm-evaluation",
          },
          {
            id: "ai-llm-production",
            title: "Cost, Observability & Security",
            description:
              "Production-ready AI: κόστος ανά token, prompt caching, latency, observability, rate limits/retries και άμυνα σε prompt injection.",
            project: "Σκλήρυνση ενός AI feature: caching, metrics, backoff, anti-injection.",
            skills: ["cost", "prompt caching", "prompt injection"],
            href: "/lessons/ai-llm-production",
          },
        ],
      },
    ],
  },
  {
    id: "architecture-system-design",
    title: "Architecture & System Design",
    description: "Μαθαίνεις πότε διαλέγεις monolith, modular monolith, microservices ή hybrid architecture.",
    lessons: [
      {
        id: "architecture-monolith-microservices",
        title: "Monolith, Microservices & Hybrid Architecture",
        description: "Πώς οργανώνεις ένα product από απλό monolith μέχρι ανεξάρτητα services.",
        project: "Architecture map για fullstack SaaS με core app και ξεχωριστά services.",
        skills: ["monolith", "microservices", "boundaries"],
        href: "/lessons/architecture-monolith-microservices",
      },
    ],
  },
  {
    id: "databases",
    title: "Databases",
    description:
      "Από relational modeling μέχρι NoSQL και production: SQL, NoSQL, caching με Redis και πώς διαλέγεις engine — σε interview βάθος.",
    lessons: [
      {
        id: "sql",
        title: "SQL (Relational Databases)",
        description:
          "Από το data modeling μέχρι production: πλήρες relational mastery track με schema design, queries, indexing, transactions, ORMs, migrations και scaling — σε interview βάθος.",
        lessons: [
          {
            id: "db-relational-modeling",
            title: "Relational Modeling & Normalization",
            description: "Tables, primary/foreign keys, σχέσεις (1-1, 1-N, N-N), normalization και πότε denormalize.",
            project: "Σχεδιασμός schema για e-shop με σωστές σχέσεις.",
            skills: ["keys", "relationships", "normalization"],
            href: "/lessons/db-relational-modeling",
          },
          {
            id: "db-sql-queries",
            title: "SQL Queries & Joins",
            description: "SELECT/WHERE, JOIN types, GROUP BY, aggregations, subqueries και CTEs.",
            project: "Analytics queries πάνω σε relational dataset.",
            skills: ["JOIN", "GROUP BY", "subqueries"],
            href: "/lessons/db-sql-queries",
          },
          {
            id: "db-indexing-performance",
            title: "Indexing & Query Performance",
            description: "B-tree indexes, EXPLAIN/query plans, composite indexes και πότε ένα index βλάπτει.",
            project: "Βελτιστοποίηση αργού query με index και μέτρηση.",
            skills: ["indexes", "EXPLAIN", "query plan"],
            href: "/lessons/db-indexing-performance",
          },
          {
            id: "db-transactions-acid",
            title: "Transactions, ACID & Isolation",
            description: "ACID, isolation levels, locking, deadlocks και race conditions σε concurrent writes.",
            project: "Money transfer με transaction που αντέχει concurrency.",
            skills: ["ACID", "isolation", "locking"],
            href: "/lessons/db-transactions-acid",
          },
          {
            id: "db-orm-n-plus-one",
            title: "ORMs, N+1 & Data Access",
            description: "ORM vs raw SQL, το N+1 problem, eager/lazy loading και connection pooling.",
            project: "Refactor data layer χωρίς N+1, με pooling.",
            skills: ["ORM", "N+1", "pooling"],
            href: "/lessons/db-orm-n-plus-one",
          },
          {
            id: "db-migrations-schema",
            title: "Schema Migrations & Evolution",
            description: "Migrations, versioning, zero-downtime αλλαγές, backfills και rollback strategy.",
            project: "Zero-downtime schema change με migration + backfill.",
            skills: ["migrations", "zero-downtime", "backfill"],
            href: "/lessons/db-migrations-schema",
          },
          {
            id: "db-scaling-replication",
            title: "Scaling, Replication & Partitioning",
            description: "Read replicas, replication lag, sharding/partitioning, connection limits και caching layer.",
            project: "Scaling plan για read-heavy service.",
            skills: ["replication", "sharding", "scaling"],
            href: "/lessons/db-scaling-replication",
          },
          {
            id: "db-design-interview",
            title: "Schema Design & Interview Practice",
            description: "Πρακτικό relational data modeling, trade-offs, κλασικές SQL ερωτήσεις και πώς απαντάς σε design.",
            project: "Σχεδιασμός schema για πραγματικό feature από την αρχή.",
            skills: ["design", "trade-offs", "interview"],
            href: "/lessons/db-design-interview",
          },
        ],
      },
      {
        id: "nosql",
        title: "NoSQL (Non-Relational)",
        description:
          "Από τους τύπους NoSQL μέχρι production data modeling: document, key-value, wide-column, access-pattern design, consistency/CAP και πότε διαλέγεις τι — σε interview βάθος.",
        lessons: [
          {
            id: "nosql-foundations",
            title: "NoSQL Foundations",
            description: "Οι 4 τύποι, SQL vs NoSQL, ACID vs BASE, CAP theorem και πότε φεύγεις από relational.",
            project: "Χάρτης: ποιος τύπος NoSQL για ποιο πρόβλημα και γιατί.",
            skills: ["NoSQL types", "BASE", "CAP"],
            href: "/lessons/nosql-foundations",
          },
          {
            id: "nosql-document",
            title: "Document Databases (MongoDB)",
            description: "Document modeling, embed vs reference, queries, indexes και aggregation pipeline.",
            project: "Document schema για blog με σωστές αποφάσεις embed/reference.",
            skills: ["documents", "embed/reference", "aggregation"],
            href: "/lessons/nosql-document",
          },
          {
            id: "nosql-key-value",
            title: "Key-Value Stores (Redis & DynamoDB)",
            description: "Key-value model, TTL, access patterns, partition keys και πότε ταιριάζει.",
            project: "Key design για session/cart/leaderboard σε key-value store.",
            skills: ["key-value", "TTL", "partition key"],
            href: "/lessons/nosql-key-value",
          },
          {
            id: "nosql-wide-column",
            title: "Wide-Column Stores (Cassandra)",
            description: "Partition & clustering keys, query-first design, write-heavy workloads και tunable consistency.",
            project: "Cassandra table design από access patterns ενός feed.",
            skills: ["partition key", "query-first", "write-heavy"],
            href: "/lessons/nosql-wide-column",
          },
          {
            id: "nosql-data-modeling",
            title: "NoSQL Data Modeling",
            description: "Access-pattern-driven design, denormalization, single-table design και σχέσεις χωρίς joins.",
            project: "Single-table design για app με πολλαπλά access patterns.",
            skills: ["denormalization", "single-table", "access patterns"],
            href: "/lessons/nosql-data-modeling",
          },
          {
            id: "nosql-consistency-scaling",
            title: "Consistency, Replication & Scaling",
            description: "Eventual consistency, quorum (R+W>N), replication, sharding, conflict resolution και PACELC.",
            project: "Consistency/scaling plan για distributed NoSQL store.",
            skills: ["eventual consistency", "quorum", "sharding"],
            href: "/lessons/nosql-consistency-scaling",
          },
          {
            id: "nosql-choosing-polyglot",
            title: "Choosing a Store & Polyglot Persistence",
            description: "Decision framework SQL vs NoSQL, polyglot persistence, migration considerations και interview practice.",
            project: "Διάλεξε & δικαιολόγησε stores για ένα multi-feature product.",
            skills: ["decision", "polyglot", "interview"],
            href: "/lessons/nosql-choosing-polyglot",
          },
        ],
      },
      {
        id: "redis-caching-sessions",
        title: "Redis, Caching & Sessions",
        description: "Key-value storage για cache, TTL, sessions, rate limits, queues και Pub/Sub.",
        project: "Cached API response με TTL και session lookup.",
        skills: ["Redis", "cache", "TTL"],
        href: "/lessons/redis-caching-sessions",
      },
      {
        id: "db-engines-compared",
        title: "Choosing a Database Engine",
        description: "PostgreSQL vs MySQL vs SQLite vs MongoDB: διαφορές, πότε ποιο, embedded vs server και operational concerns.",
        project: "Διάλεξε & δικαιολόγησε engine για 3 διαφορετικά apps.",
        skills: ["PostgreSQL", "MySQL", "SQLite"],
        href: "/lessons/db-engines-compared",
      },
    ],
  },
  {
    id: "auth-security",
    title: "Auth & Security",
    description: "Προστατεύεις χρήστες, routes και APIs: authentication, authorization και web security.",
    lessons: [
      {
        id: "authentication",
        title: "Authentication & Authorization",
        description: "Login, sessions, JWT/OAuth και προστατευμένες σελίδες.",
        project: "Protected dashboard.",
        skills: ["sessions", "JWT", "OAuth"],
        href: "/lessons/authentication",
      },
      {
        id: "web-security",
        title: "Web Security Basics",
        description: "XSS, CSRF, secrets, validation και ασφαλή server-side όρια.",
        project: "Secure form handling.",
        skills: ["XSS", "CSRF", "validation"],
        href: "/lessons/web-security",
      },
    ],
  },
  {
    id: "cloud-devops",
    title: "Cloud & DevOps",
    description: "Κάνεις deploy, διαβάζεις logs και οργανώνεις delivery pipeline.",
    lessons: [
      {
        id: "linux",
        title: "Linux Server & Operations",
        description:
          "Από το command line basics (στο Developer Workflow) στο production server: Linux με SSH, hardened πρόσβαση, και πώς κρατάς processes/services ζωντανά με logs — η βάση κάθε backend/DevOps δουλειάς.",
        lessons: [
          {
            id: "linux-server-ssh",
            title: "Linux Server & SSH",
            description: "VPS, SSH keys vs passwords, scp/rsync, users/sudo, permissions (chmod/chown), firewall/ports και reverse proxy.",
            project: "Στήσε key-based, hardened πρόσβαση σε φρέσκο VPS.",
            skills: ["SSH", "permissions", "reverse proxy"],
            href: "/lessons/linux-server-ssh",
          },
          {
            id: "linux-processes-logs-services",
            title: "Processes, Logs & Services",
            description: "Processes & signals, graceful shutdown, ports, systemd services με auto-restart, journalctl/logs και cron.",
            project: "Κάνε ένα Node app production-grade systemd service.",
            skills: ["systemd", "signals", "journalctl"],
            href: "/lessons/linux-processes-logs-services",
          },
        ],
      },
      {
        id: "deployment",
        title: "Deployment & Cloud",
        description: "Build, environment variables, deploy σε Vercel/AWS/Azure/GCP και basic cloud services.",
        project: "Deploy του fullstack project.",
        skills: ["AWS", "Azure/GCP", "env vars"],
        href: "/lessons/deployment",
      },
      {
        id: "docker-ci-cd",
        title: "Docker & CI/CD",
        description: "Containers, GitHub Actions, automated checks και release workflow.",
        project: "Dockerized app with CI.",
        skills: ["Docker", "GitHub Actions", "CI/CD"],
        href: "/lessons/docker-ci-cd",
      },
      {
        id: "observability",
        title: "Logs, Monitoring & Observability",
        description: "Διαβάζεις logs, παρακολουθείς errors και καταλαβαίνεις τι συμβαίνει στην παραγωγή.",
        project: "App with structured logs and error tracking.",
        skills: ["logs", "Sentry", "metrics"],
        href: "/lessons/observability",
      },
      {
        id: "capstone",
        title: "Fullstack Capstone",
        description: "Συνδυάζεις frontend, backend, database, auth και deploy.",
        project: "Production-style fullstack app.",
        skills: ["frontend", "backend", "database"],
        href: "/lessons/capstone",
      },
      {
        id: "final-assessment",
        title: "Final Assessment",
        description: "Rubric για να κρίνεις αν το capstone είναι portfolio-ready και interview-ready.",
        project: "Self-assessment scorecard για το capstone.",
        skills: ["rubric", "capstone", "interview"],
        href: "/lessons/final-assessment",
      },
    ],
  },
];

export type LessonWithSection = Lesson & {
  sectionId: string;
  sectionTitle: string;
  sectionIndex: number;
  groupTitle?: string;
  estimatedMinutes: number;
};

export const allLessons: LessonWithSection[] = curriculum.flatMap((section, sectionIndex) =>
  section.lessons.flatMap((item) => {
    const base = { sectionId: section.id, sectionTitle: section.title, sectionIndex };
    if (isLessonGroup(item)) {
      return item.lessons.map((lesson) => ({
        ...lesson,
        ...base,
        groupTitle: item.title,
        estimatedMinutes: lessonDurationsMinutes[lesson.id] ?? 60,
      }));
    }
    return [{ ...item, ...base, estimatedMinutes: lessonDurationsMinutes[item.id] ?? 60 }];
  }),
);

export const totalEstimatedMinutes = allLessons.reduce((total, lesson) => total + lesson.estimatedMinutes, 0);

export function getLessonsEstimatedMinutes(lessons: Lesson[]) {
  return lessons.reduce((total, lesson) => total + (lessonDurationsMinutes[lesson.id] ?? 60), 0);
}

export function formatDuration(minutes: number) {
  if (minutes < 60) return `${minutes} λεπτά`;

  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  const hourLabel = hours === 1 ? "ώρα" : "ώρες";

  if (remainingMinutes === 0) return `${hours} ${hourLabel}`;
  return `${hours} ${hourLabel} ${remainingMinutes} λεπτά`;
}

export function getLessonBySlug(slug: string): LessonWithSection | undefined {
  return allLessons.find((lesson) => lesson.href === `/lessons/${slug}`);
}

export function getAdjacentLessons(slug: string): {
  previous: LessonWithSection | null;
  next: LessonWithSection | null;
} {
  const index = allLessons.findIndex((lesson) => lesson.href === `/lessons/${slug}`);
  if (index === -1) return { previous: null, next: null };
  return {
    previous: index > 0 ? allLessons[index - 1] : null,
    next: index < allLessons.length - 1 ? allLessons[index + 1] : null,
  };
}
